### ISSUE TITLE
Not getting the devices

### ISSUE THREAD

**Issue by IbrahimEzzatSaad** [hmz777/NetStalker#3]
Well at first try of the program, it was amazing and I had all devices in the network but seconds after I think all the devices disappear and its only showing me my gateway and my PC device. how can i fix that?

**Comment by hmz777** [comment]
@IbrahimEzzatSaad well, this never happened to me at all, and there are some factors to take into consideration here:
- Your NIC might be causing the problem since when i made this software i only tried it on mine so i can't guarantee it will work on other network cards.
- NetStalker has a time out for each device in order to track disconnected devices, i think that at some point you got disconneccted from your network and thats why the devices disappeared.

If you can provide me with more information it would be good.

**Comment by hmz777** [comment]
Closed for inactivity.
